// Database Titik Pemantauan Perairan AquaVoice
export const WATER_MONITORING_LOCATIONS = [
  {
    id: 'LOC-001',
    name: 'Sektor 1 - Muara Angke',
    region: 'DKI Jakarta',
    sector: 'Sektor 1',
    lat: -6.1089,
    lng: 106.7744,
    riskLevel: 'DANGER', // SAFE, WARNING, DANGER
    riskLabel: 'Bahaya (Danger)',
    riskBadgeClass: 'badge-danger',
    markerColor: '#ef4444', // Red
    waterScore: 42,
    metrics: {
      ph: 6.2,
      do: 3.1,
      turbidity: 12.5,
      salinity: 28.4,
      temp: 30.2,
    },
    lastUpdated: '10 menit yang lalu',
    description: 'Terdeteksi lonjakan keruhan tinggi dan defisit oksigen (DO < 3.5 mg/L). Potential Anoxia.',
  },
  {
    id: 'LOC-002',
    name: 'Sektor 2 - Teluk Jakarta Utara',
    region: 'DKI Jakarta',
    sector: 'Sektor 2',
    lat: -6.0821,
    lng: 106.8412,
    riskLevel: 'WARNING',
    riskLabel: 'Waspada (Warning)',
    riskBadgeClass: 'badge-warning',
    markerColor: '#f59e0b', // Amber/Yellow
    waterScore: 68,
    metrics: {
      ph: 7.9,
      do: 4.8,
      turbidity: 6.2,
      salinity: 31.0,
      temp: 29.1,
    },
    lastUpdated: '5 menit yang lalu',
    description: 'Tingkat keruhan sedikit di atas batas baku mutu. Parameter lain relatif stabil.',
  },
  {
    id: 'LOC-003',
    name: 'Sektor 3 - Pantai Kenjeran',
    region: 'Jawa Timur',
    sector: 'Sektor 3',
    lat: -7.2381,
    lng: 112.7963,
    riskLevel: 'SAFE',
    riskLabel: 'Aman (Safe)',
    riskBadgeClass: 'badge-safe',
    markerColor: '#10b981', // Emerald/Green
    waterScore: 91,
    metrics: {
      ph: 7.7,
      do: 6.8,
      turbidity: 2.1,
      salinity: 32.5,
      temp: 28.4,
    },
    lastUpdated: '2 menit yang lalu',
    description: 'Kondisi perairan sangat baik. Seluruh indikator berada pada rentang baku mutu ideal.',
  },
  {
    id: 'LOC-004',
    name: 'Sektor 4 - Tambak Buleleng',
    region: 'Bali',
    sector: 'Sektor 4',
    lat: -8.112,
    lng: 115.0882,
    riskLevel: 'SAFE',
    riskLabel: 'Aman (Safe)',
    riskBadgeClass: 'badge-safe',
    markerColor: '#10b981',
    waterScore: 88,
    metrics: {
      ph: 7.6,
      do: 6.2,
      turbidity: 3.0,
      salinity: 33.1,
      temp: 28.8,
    },
    lastUpdated: '15 menit yang lalu',
    description: 'Sirkulasi air tambak dalam kondisi normal, ideal untuk budidaya udang vaname.',
  },
  {
    id: 'LOC-005',
    name: 'Sektor 5 - Pesisir Panjang',
    region: 'Lampung',
    sector: 'Sektor 5',
    lat: -5.4489,
    lng: 105.3122,
    riskLevel: 'DANGER',
    riskLabel: 'Bahaya (Danger)',
    riskBadgeClass: 'badge-danger',
    markerColor: '#ef4444',
    waterScore: 38,
    metrics: {
      ph: 8.8,
      do: 2.9,
      turbidity: 18.0,
      salinity: 26.0,
      temp: 31.5,
    },
    lastUpdated: '1 menit yang lalu',
    description: 'Laporan warga mengindikasikan jejak tumpahan cairan oli/minyak di garis pantai.',
  },
];